# The viewport's copies of Blender's world HDRIs (datafiles/studiolights/world),
# which Material Preview lights with. Runs inside Blender; regenerate with the
# engine image when Blender's set changes:
#
#   docker run --rm --entrypoint blender -v "$PWD:/out" cycls/cycls-render:<tag> \
#     -b --python /out/scripts/worlds.py          (from studio/)
#
# Each map is area-averaged to 64x32 (rows top to bottom), RGBE-packed, base64.
import base64
import glob
import json
import os

import bpy
import numpy as np

W, H = 64, 32
out = {}
for path in sorted(glob.glob(os.path.join(bpy.utils.system_resource("DATAFILES", path="studiolights/world"), "*.exr"))):
    name = os.path.basename(path)[:-4]
    img = bpy.data.images.load(path)
    w, h = img.size
    px = np.empty(w * h * 4, dtype=np.float32)
    img.pixels.foreach_get(px)
    px = px.reshape(h, w, 4)[::-1, :, :3]                     # Blender's rows run bottom up
    small = px.reshape(H, h // H, W, w // W, 3).mean(axis=(1, 3))
    m = small.max(axis=2)
    e = np.ceil(np.log2(np.maximum(m, 1e-32)))
    scale = np.where(m > 1e-32, 256.0 / np.exp2(e), 0)
    rgbe = np.zeros((H, W, 4), dtype=np.uint8)
    rgbe[..., :3] = np.clip(np.floor(small * scale[..., None]), 0, 255)
    rgbe[..., 3] = np.where(m > 1e-32, e + 128, 0)
    out[name] = base64.b64encode(rgbe.tobytes()).decode()
    print(name, w, h)

with open("/out/src/worlds.js", "w") as f:
    f.write("// Generated by scripts/worlds.py from Blender's world HDRIs: 64x32 RGBE, rows top down, base64.\n")
    f.write("export const WORLDS = " + json.dumps(out, indent=1) + ";\n")
